import atelierScene from './assets/atelier-scene.svg';
import launchScene from './assets/launch-scene.svg';
import signalScene from './assets/signal-scene.svg';
import deviceHero from './assets/device-hero.svg';
import meshHero from './assets/mesh-hero.svg';
import orbitHero from './assets/orbit-hero.svg';
import type { EditorDocument, ScenePreset } from './types';

const CANVAS_WIDTH = 1280;
const CANVAS_HEIGHT = 840;

function makeTextLayer(
  id: string,
  name: string,
  text: string,
  x: number,
  y: number,
  width: number,
  fontSize: number,
  fontFamily: string,
  fontWeight: number,
  fill: string,
  align: 'left' | 'center' | 'right' = 'left',
) {
  return {
    id,
    type: 'text' as const,
    name,
    text,
    x,
    y,
    width,
    fontSize,
    fontFamily,
    fontWeight,
    fill,
    align,
    lineHeight: 1.08,
    letterSpacing: fontSize >= 48 ? -0.8 : 0,
    rotation: 0,
    opacity: 1,
    visible: true,
    locked: false,
  };
}

function makeImageLayer(
  id: string,
  name: string,
  src: string,
  x: number,
  y: number,
  width: number,
  height: number,
  stroke = '#ffffff',
) {
  return {
    id,
    type: 'image' as const,
    name,
    src,
    x,
    y,
    width,
    height,
    stroke,
    strokeWidth: 1.5,
    shadowColor: '#091018',
    shadowBlur: 26,
    shadowOpacity: 0.28,
    rotation: -4,
    opacity: 1,
    visible: true,
    locked: false,
  };
}

export const SCENE_PRESETS: ScenePreset[] = [
  {
    id: 'atelier',
    name: 'Atelier Board',
    kicker: 'Editorial Atmosphere',
    label: 'EDITORIAL WORKBOARD',
    hint: '适合封面图、品牌主视觉和长标题排版，先定氛围，再调文案层级。',
    thumbnail: atelierScene,
    document: {
      canvas: { width: CANVAS_WIDTH, height: CANVAS_HEIGHT },
      background: {
        color: '#0b1420',
        imageSrc: atelierScene,
        overlayColor: '#09131c',
        overlayOpacity: 0.22,
        imageOpacity: 0.98,
        fit: 'cover',
      },
      layers: [
        makeTextLayer(
          'atelier-kicker',
          'Eyebrow',
          'SCENE 01 / CREATIVE OPERATIONS',
          92,
          86,
          480,
          17,
          'IBM Plex Sans',
          600,
          '#8fdcff',
        ),
        makeTextLayer(
          'atelier-headline',
          'Headline',
          'Build the visual\nbefore the brief\nslows you down',
          92,
          136,
          660,
          76,
          'Sora',
          700,
          '#f8f3ea',
        ),
        makeTextLayer(
          'atelier-body',
          'Body',
          '背景图、文案、主视觉和图层动作被放在同一块工作台里。\n先切气质，再改内容，不再被零散面板打断。',
          96,
          516,
          470,
          24,
          'IBM Plex Sans',
          500,
          '#dce8ef',
        ),
        makeTextLayer(
          'atelier-footer',
          'Footer',
          'Preset / Background / Copy / Export',
          92,
          724,
          420,
          18,
          'IBM Plex Sans',
          500,
          '#f29f7c',
        ),
        makeImageLayer('atelier-hero', 'Hero Artwork', orbitHero, 774, 118, 404, 584, '#8dd9ff'),
      ],
    },
  },
  {
    id: 'launch',
    name: 'Launch Shelf',
    kicker: 'Product Story',
    label: 'PRODUCT LAUNCH BOARD',
    hint: '适合产品海报、卖点信息和封面版式，整体节奏更清晰，CTA 更靠前。',
    thumbnail: launchScene,
    document: {
      canvas: { width: CANVAS_WIDTH, height: CANVAS_HEIGHT },
      background: {
        color: '#efe4d4',
        imageSrc: launchScene,
        overlayColor: '#f5ead9',
        overlayOpacity: 0.18,
        imageOpacity: 0.94,
        fit: 'cover',
      },
      layers: [
        makeTextLayer(
          'launch-kicker',
          'Eyebrow',
          'READY-TO-SHIP EDITOR',
          92,
          92,
          420,
          17,
          'IBM Plex Sans',
          600,
          '#c45b36',
        ),
        makeTextLayer(
          'launch-headline',
          'Headline',
          'Move faster when\nyour editor already\nfeels like a studio',
          92,
          154,
          660,
          70,
          'Sora',
          700,
          '#1b2431',
        ),
        makeTextLayer(
          'launch-body',
          'Body',
          '右侧直接改标题和正文，左侧一键切换场景情绪。\n面板不是堆功能，而是把成品路径收短。',
          96,
          502,
          500,
          24,
          'IBM Plex Sans',
          500,
          '#36414d',
        ),
        makeTextLayer(
          'launch-footer',
          'CTA',
          'Swap background. Tune copy. Export the board.',
          92,
          712,
          520,
          19,
          'IBM Plex Sans',
          600,
          '#8a4020',
        ),
        makeImageLayer('launch-hero', 'Product Card', deviceHero, 770, 116, 386, 578, '#ff845f'),
      ],
    },
  },
  {
    id: 'signal',
    name: 'Signal Room',
    kicker: 'Sharper System',
    label: 'CAMPAIGN CONTROL ROOM',
    hint: '适合科技感画面、活动 KV 和更强控制欲的工作台风格。',
    thumbnail: signalScene,
    document: {
      canvas: { width: CANVAS_WIDTH, height: CANVAS_HEIGHT },
      background: {
        color: '#0f1719',
        imageSrc: signalScene,
        overlayColor: '#061012',
        overlayOpacity: 0.2,
        imageOpacity: 0.98,
        fit: 'cover',
      },
      layers: [
        makeTextLayer(
          'signal-kicker',
          'Eyebrow',
          'SYSTEM / LAYERS / COPY CONTROL',
          92,
          92,
          460,
          17,
          'IBM Plex Sans',
          600,
          '#6de2cf',
        ),
        makeTextLayer(
          'signal-headline',
          'Headline',
          'Sharper controls.\nCleaner layers.\nFewer dead ends.',
          92,
          154,
          640,
          74,
          'Sora',
          700,
          '#edf7f0',
        ),
        makeTextLayer(
          'signal-body',
          'Body',
          '背景替换、文案改写、图片层替换和导出不再分散。\n每个动作都围绕“更快出成品”来组织。',
          96,
          506,
          500,
          24,
          'IBM Plex Sans',
          500,
          '#c5d8d4',
        ),
        makeTextLayer(
          'signal-footer',
          'Footer',
          'Focus / Reorder / Duplicate / Export',
          92,
          712,
          480,
          18,
          'IBM Plex Sans',
          600,
          '#f2c66d',
        ),
        makeImageLayer('signal-hero', 'Signal Graphic', meshHero, 768, 118, 392, 576, '#6de2cf'),
      ],
    },
  },
];

export function cloneDocument(document: EditorDocument): EditorDocument {
  return JSON.parse(JSON.stringify(document)) as EditorDocument;
}

export function getPresetById(presetId: ScenePreset['id']) {
  return SCENE_PRESETS.find((preset) => preset.id === presetId) ?? SCENE_PRESETS[0];
}
